{"level":"info","datetime":"2021-04-04T17:31:16.647Z","logger":"Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:31:16.664Z","logger":"Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:31:16.678Z","logger":"Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:31:16.680Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server","caller":"logs/log.go:39","msg":"Invalid User","type":"process","error":"sql: no rows in result set"}
{"level":"info","datetime":"2021-04-04T17:31:16.692Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:31:16.715Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:31:16.730Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:34:52.474Z","logger":"Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:34:52.493Z","logger":"Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:34:52.504Z","logger":"Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:34:52.507Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server","caller":"logs/log.go:39","msg":"Invalid User","type":"process","error":"sql: no rows in result set"}
{"level":"info","datetime":"2021-04-04T17:34:52.519Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:34:52.537Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:34:52.550Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:35:41.642Z","logger":"Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:35:41.657Z","logger":"Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:35:41.668Z","logger":"Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:35:41.671Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server","caller":"logs/log.go:39","msg":"Invalid User","type":"process","error":"sql: no rows in result set"}
{"level":"info","datetime":"2021-04-04T17:35:41.683Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:35:41.727Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:35:41.749Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:36:08.994Z","logger":"Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:36:09.011Z","logger":"Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:36:09.022Z","logger":"Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:36:09.027Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server","caller":"logs/log.go:39","msg":"Invalid User","type":"process","error":"sql: no rows in result set"}
{"level":"info","datetime":"2021-04-04T17:36:09.040Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:36:09.061Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:36:09.077Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:39:12.884Z","logger":"Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:39:12.901Z","logger":"Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:39:12.913Z","logger":"Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:39:12.915Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server","caller":"logs/log.go:39","msg":"Invalid User","type":"process","error":"sql: no rows in result set"}
{"level":"info","datetime":"2021-04-04T17:39:12.928Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:39:12.947Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:39:12.966Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:42:34.365Z","logger":"Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:42:34.380Z","logger":"Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:42:34.393Z","logger":"Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:42:34.398Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server","caller":"logs/log.go:39","msg":"Invalid User","type":"process","error":"sql: no rows in result set"}
{"level":"info","datetime":"2021-04-04T17:42:34.410Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:42:34.430Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:42:34.451Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:44:24.927Z","logger":"Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:44:24.944Z","logger":"Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:44:24.959Z","logger":"Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:44:24.967Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server","caller":"logs/log.go:39","msg":"Invalid User","type":"process","error":"sql: no rows in result set"}
{"level":"info","datetime":"2021-04-04T17:44:24.980Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:44:25.006Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:44:25.027Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:45:14.221Z","logger":"Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:45:14.237Z","logger":"Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:45:14.249Z","logger":"Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:45:14.254Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server","caller":"logs/log.go:39","msg":"Invalid User","type":"process","error":"sql: no rows in result set"}
{"level":"info","datetime":"2021-04-04T17:45:14.265Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:45:14.286Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:45:14.306Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:46:00.586Z","logger":"Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:46:00.610Z","logger":"Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:46:00.626Z","logger":"Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:46:00.632Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server","caller":"logs/log.go:39","msg":"Invalid User","type":"process","error":"sql: no rows in result set"}
{"level":"info","datetime":"2021-04-04T17:46:00.645Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:46:00.670Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-04T17:46:00.686Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-05T11:09:42.408Z","logger":"Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-05T11:09:42.453Z","logger":"Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-05T11:09:42.469Z","logger":"Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-05T11:09:42.472Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server","caller":"logs/log.go:39","msg":"Invalid User","type":"process","error":"sql: no rows in result set"}
{"level":"info","datetime":"2021-04-05T11:09:42.485Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-05T11:09:42.546Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-05T11:09:42.558Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-05T11:12:12.325Z","logger":"Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-05T11:12:12.355Z","logger":"Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-05T11:12:12.370Z","logger":"Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-05T11:12:12.377Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server","caller":"logs/log.go:39","msg":"Invalid User","type":"process","error":"sql: no rows in result set"}
{"level":"info","datetime":"2021-04-05T11:12:12.390Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"info","datetime":"2021-04-05T11:12:12.413Z","logger":"Postgres.Server.Postgres.Server.Postgres.Server.Postgres.Server.Postgres","caller":"logs/log.go:39","msg":"Connection Postgres successful","type":"process","error":null}
{"level":"error","datetime":"2021-04-05T13:45:16.376Z","logger":"Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.3:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:78\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:46\ngithub.com/manabie-com/togo/internal/transport.getServer\n\t/app/internal/transport/integration_test.go:179\ngithub.com/manabie-com/togo/internal/transport.TestLogin.func4\n\t/app/internal/transport/integration_test.go:55\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1050"}
{"level":"error","datetime":"2021-04-05T13:45:26.389Z","logger":"Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.3:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:78\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:46\ngithub.com/manabie-com/togo/internal/transport.getServer\n\t/app/internal/transport/integration_test.go:179\ngithub.com/manabie-com/togo/internal/transport.TestLogin.func4\n\t/app/internal/transport/integration_test.go:55\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1050"}
{"level":"error","datetime":"2021-04-05T13:45:36.394Z","logger":"Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.3:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:78\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:46\ngithub.com/manabie-com/togo/internal/transport.getServer\n\t/app/internal/transport/integration_test.go:179\ngithub.com/manabie-com/togo/internal/transport.TestLogin.func4\n\t/app/internal/transport/integration_test.go:55\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1050"}
{"level":"error","datetime":"2021-04-05T13:45:46.406Z","logger":"Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.3:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:78\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:46\ngithub.com/manabie-com/togo/internal/transport.getServer\n\t/app/internal/transport/integration_test.go:179\ngithub.com/manabie-com/togo/internal/transport.TestLogin.func4\n\t/app/internal/transport/integration_test.go:55\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1050"}
{"level":"error","datetime":"2021-04-05T13:45:56.436Z","logger":"Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.3:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:78\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:46\ngithub.com/manabie-com/togo/internal/transport.getServer\n\t/app/internal/transport/integration_test.go:179\ngithub.com/manabie-com/togo/internal/transport.TestLogin.func4\n\t/app/internal/transport/integration_test.go:55\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1050"}
{"level":"error","datetime":"2021-04-05T13:46:06.452Z","logger":"Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.3:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:78\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:46\ngithub.com/manabie-com/togo/internal/transport.getServer\n\t/app/internal/transport/integration_test.go:179\ngithub.com/manabie-com/togo/internal/transport.TestLogin.func4\n\t/app/internal/transport/integration_test.go:55\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1050"}
{"level":"error","datetime":"2021-04-05T13:46:16.496Z","logger":"Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.3:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:78\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:46\ngithub.com/manabie-com/togo/internal/transport.getServer\n\t/app/internal/transport/integration_test.go:179\ngithub.com/manabie-com/togo/internal/transport.TestLogin.func4\n\t/app/internal/transport/integration_test.go:55\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1050"}
{"level":"error","datetime":"2021-04-05T13:46:26.510Z","logger":"Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.3:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:78\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:46\ngithub.com/manabie-com/togo/internal/transport.getServer\n\t/app/internal/transport/integration_test.go:179\ngithub.com/manabie-com/togo/internal/transport.TestLogin.func4\n\t/app/internal/transport/integration_test.go:55\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1050"}
{"level":"error","datetime":"2021-04-05T13:46:36.518Z","logger":"Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.3:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:78\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:46\ngithub.com/manabie-com/togo/internal/transport.getServer\n\t/app/internal/transport/integration_test.go:179\ngithub.com/manabie-com/togo/internal/transport.TestLogin.func4\n\t/app/internal/transport/integration_test.go:55\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1050"}
{"level":"error","datetime":"2021-04-05T13:46:46.530Z","logger":"Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.3:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:78\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:46\ngithub.com/manabie-com/togo/internal/transport.getServer\n\t/app/internal/transport/integration_test.go:179\ngithub.com/manabie-com/togo/internal/transport.TestLogin.func4\n\t/app/internal/transport/integration_test.go:55\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1050"}
{"level":"error","datetime":"2021-04-05T13:46:58.696Z","logger":"Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.3:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:78\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:46\ngithub.com/manabie-com/togo/internal/transport.getServer\n\t/app/internal/transport/integration_test.go:179\ngithub.com/manabie-com/togo/internal/transport.TestLogin.func4\n\t/app/internal/transport/integration_test.go:55\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1050"}
{"level":"error","datetime":"2021-04-05T13:47:08.703Z","logger":"Postgres","caller":"logs/log.go:44","msg":"Try to ping postgres","type":"process","error":"dial tcp 172.20.0.3:5432: connect: connection refused","stacktrace":"github.com/manabie-com/togo/internal/logs.(*Logger).Error\n\t/app/internal/logs/log.go:44\ngithub.com/manabie-com/togo/internal/storages/postgres.(*Postgres).pingDB\n\t/app/internal/storages/postgres/db.go:78\ngithub.com/manabie-com/togo/internal/storages/postgres.NewPostgres\n\t/app/internal/storages/postgres/db.go:46\ngithub.com/manabie-com/togo/internal/transport.getServer\n\t/app/internal/transport/integration_test.go:179\ngithub.com/manabie-com/togo/internal/transport.TestLogin.func4\n\t/app/internal/transport/integration_test.go:55\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1050"}
